VAPID_PUBLIC_KEY = "BElPXNitgoVsi7Nxf8lUTlCtD_MeW-7GKdLLVVd5j7Rceyc7K31IeoEozBOuFMa8nuKCBH09mJbXSY3yGtP88pU" 
VAPID_PRIVATE_KEY = "aA-5BtI9sylpx9MecKJLkmCtWGDakCfa1rMsRs2s0tg" 
VAPID_CLAIM_EMAIL = "abraryaser00@gmail.com"